# Generated by Django 5.0.1 on 2024-02-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groceries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groceryitem",
            name="price",
            field=models.IntegerField(),
        ),
    ]
